//! The versioned local-model catalog.
//!
//! Per the task's Technical Notes, the catalog is **data, not code**: a
//! versioned TOML document mapping a model name to its GGUF URL, expected
//! SHA-256, download size, minimum RAM, and the OQ-3 hardware band it serves.
//! The daemon can drop in a newer catalog (bumping `version`) without a
//! `teton-inference` release. A default catalog is embedded in the binary via
//! [`Catalog::bundled`].
//!
//! The catalog also encodes the model *ordering* used for step-down: models are
//! ranked by `ram_floor_bytes` (ties broken by `size_bytes`), and both the probe
//! (`probe::decide`) and the benchmark/pressure step-down walk that order.
//!
//! ## Revision pinning and digest provenance
//!
//! Every URL is a HuggingFace `.../resolve/<commit-sha>/<file>.gguf` that pins an
//! **immutable 40-hex commit SHA**, never a moving ref like `main` (BR-15): a
//! moving ref would let the bytes change under a fixed `sha256` and turn the
//! download integrity check into spurious corruption failures. [`Catalog::validate`]
//! is the enforcement, and the bundled catalog is asserted against it by the
//! tests below.
//!
//! The digests are not hand-typed. `data/models.toml` is generated by
//! `tools/refresh-catalog.py` from HuggingFace's LFS metadata — `lfs.oid` *is*
//! the artifact's SHA-256 and `lfs.size` its length, both readable without
//! transferring a byte of the multi-GB weights (REQ-547 architecture D-1).
//!
//! ## Base-URL override
//!
//! [`ModelEntry::download_url`] applies the configured `[local_model] base_url`
//! (BR-16), rewriting only the scheme/host/prefix and preserving the
//! repo/revision/file path — so a corporate mirror keeps serving the *same*
//! pinned artifact, and the `sha256` check still means what it meant.

use serde::{Deserialize, Serialize};

use crate::probe::HardwareProfile;

/// Git refs that move. Listed so a catalog that pins one gets an error naming
/// the specific hazard rather than the generic "not 40 hex characters".
const MOVING_REFS: &[&str] = &["main", "master", "head", "latest", "dev", "develop"];

/// A catalog entry that violates an invariant the downloader depends on.
///
/// Every variant carries the offending entry's `name` and a remedy, because the
/// audience is whoever is editing the catalog — not an end user.
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
pub enum CatalogError {
    /// The URL is not a HuggingFace `.../resolve/<revision>/<file>` URL, so no
    /// revision can be pinned or checked at all.
    #[error(
        "catalog entry `{name}` has a URL that is not a pinned HuggingFace artifact: `{url}`. \
         Expected the form `https://huggingface.co/<owner>/<repo>/resolve/<40-hex-commit-sha>/<file>.gguf`. \
         Regenerate the catalog with `python3 tools/refresh-catalog.py --update`."
    )]
    UnpinnableUrl {
        /// The offending entry's catalog name.
        name: String,
        /// The URL as written in the catalog.
        url: String,
    },
    /// The revision is a branch or other moving ref (BR-15).
    #[error(
        "catalog entry `{name}` pins the moving ref `{revision}` instead of a commit SHA. \
         A moving ref lets the artifact change while `sha256` stays put, which surfaces as \
         spurious corruption failures on download (BR-15). Resolve it to an immutable commit \
         SHA with `python3 tools/refresh-catalog.py --update`."
    )]
    MovingRevision {
        /// The offending entry's catalog name.
        name: String,
        /// The moving ref that was pinned.
        revision: String,
    },
    /// The revision is neither a moving ref nor a well-formed commit SHA.
    #[error(
        "catalog entry `{name}` has revision `{revision}`, which is not a commit SHA: a revision \
         must be exactly 40 lowercase hex characters (BR-15). Regenerate the catalog with \
         `python3 tools/refresh-catalog.py --update`."
    )]
    MalformedRevision {
        /// The offending entry's catalog name.
        name: String,
        /// The revision as written in the catalog.
        revision: String,
    },
    /// The `revision` field and the revision embedded in the URL disagree —
    /// the signature of a hand-edit that changed one and not the other.
    #[error(
        "catalog entry `{name}` disagrees with itself: `revision` is `{declared}` but its URL \
         resolves `{in_url}`. The digest belongs to exactly one revision, so one of the two is \
         wrong. Regenerate the catalog with `python3 tools/refresh-catalog.py --update` rather \
         than editing it by hand."
    )]
    RevisionMismatch {
        /// The offending entry's catalog name.
        name: String,
        /// The value of the `revision` field.
        declared: String,
        /// The revision segment found in the URL.
        in_url: String,
    },
    /// `sha256` is not a lowercase-hex SHA-256.
    #[error(
        "catalog entry `{name}` has sha256 `{sha256}`, which is not a SHA-256 digest: it must be \
         exactly 64 lowercase hex characters. It is HuggingFace's `lfs.oid` for the pinned file; \
         regenerate the catalog with `python3 tools/refresh-catalog.py --update`."
    )]
    MalformedDigest {
        /// The offending entry's catalog name.
        name: String,
        /// The digest as written in the catalog.
        sha256: String,
    },
    /// Two entries share a name, so [`Catalog::get`] is ambiguous.
    #[error(
        "the catalog defines `{name}` more than once. Model names are the identity used by the \
         pin, the CLI and the persisted selection, so they must be unique."
    )]
    DuplicateName {
        /// The duplicated catalog name.
        name: String,
    },
}

/// The `<repo>`, `<revision>` and `<file>` of a HuggingFace `resolve` URL.
///
/// Parsing is host-agnostic on purpose: a base-URL override (BR-16) points at a
/// mirror, and the mirror still serves the same repo/revision/file path.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct HfSource<'a> {
    /// The repository, e.g. `Qwen/Qwen2.5-Coder-7B-Instruct-GGUF`.
    pub repo: &'a str,
    /// The pinned revision, as written in the URL.
    pub revision: &'a str,
    /// The file path within the repository at that revision.
    pub file: &'a str,
}

impl<'a> HfSource<'a> {
    /// Parse `https://<host>/<repo>/resolve/<revision>/<file>`, or `None` if the
    /// URL is not in that form.
    #[must_use]
    pub fn parse(url: &'a str) -> Option<Self> {
        let path = url_path(url)?.strip_prefix('/')?;
        let (repo, rest) = path.split_once("/resolve/")?;
        let (revision, file) = rest.split_once('/')?;
        if repo.is_empty() || revision.is_empty() || file.is_empty() {
            return None;
        }
        Some(Self {
            repo,
            revision,
            file,
        })
    }
}

/// The path (and anything after it) of an absolute URL, including its leading
/// `/` — `https://h/a/b?c` becomes `/a/b?c`. `None` if `url` has no `://` or no
/// path component.
fn url_path(url: &str) -> Option<&str> {
    let authority = &url[url.find("://")? + 3..];
    let slash = authority.find('/')?;
    Some(&authority[slash..])
}

/// Is `value` exactly `len` lowercase hex characters?
fn is_lower_hex(value: &str, len: usize) -> bool {
    value.len() == len
        && value
            .bytes()
            .all(|b| matches!(b, b'0'..=b'9' | b'a'..=b'f'))
}

/// The default catalog shipped in the binary. Kept in a data file so it reads as
/// data; validated by the unit tests below.
const BUNDLED_TOML: &str = include_str!("../data/models.toml");

/// The OQ-3 hardware band a model targets. Ordered smallest-to-largest so `<`
/// and `<=` express "no bigger than this band".
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum TierBand {
    /// 1.5B-3B class, for 8-16 GiB machines.
    Small,
    /// 7B class, for 16-32 GiB machines.
    Mid,
    /// 30B-A3B class, for 32 GiB+ machines (optional).
    Large,
}

/// One catalog entry.
///
/// `size_bytes` and `ram_floor_bytes` are what the probe and disk checks read;
/// `sha256` is the integrity check the downloader verifies. Not [`Eq`] only
/// because there is no reason to constrain future numeric fields; [`PartialEq`]
/// is enough for tests.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ModelEntry {
    /// Catalog id, e.g. `qwen2.5-coder-3b`.
    pub name: String,
    /// GGUF download URL, always pinning an immutable revision:
    /// `https://huggingface.co/<repo>/resolve/<commit-sha>/<file>.gguf`.
    ///
    /// This is the *catalog* URL. What actually gets fetched is
    /// [`ModelEntry::download_url`], which applies the base-URL override.
    pub url: String,
    /// The immutable 40-hex commit SHA the URL pins (BR-15).
    ///
    /// Redundant with the revision segment of [`url`](Self::url) by design:
    /// stating it separately makes the pin greppable, and lets
    /// [`ModelEntry::validate`] catch a hand-edit that changed one and not the
    /// other — which would otherwise pair a digest with the wrong revision.
    pub revision: String,
    /// Expected lowercase-hex SHA-256 of the downloaded file.
    ///
    /// Sourced from HuggingFace's `lfs.oid` for exactly this file at exactly
    /// this revision (REQ-547 architecture D-1).
    pub sha256: String,
    /// Download size in bytes.
    pub size_bytes: u64,
    /// Minimum system RAM required to load the model, in bytes. This is a
    /// conservative *floor* that deliberately leaves headroom for the user's
    /// work (BR-8/BR-9: never degrade the machine), not the raw weight size.
    pub ram_floor_bytes: u64,
    /// The hardware band this model serves.
    pub band: TierBand,
}

impl ModelEntry {
    /// Does this model fit `profile` — enough RAM to load it and enough free
    /// disk to hold the download?
    #[must_use]
    pub fn fits(&self, profile: &HardwareProfile) -> bool {
        self.ram_floor_bytes <= profile.ram_bytes && self.size_bytes <= profile.free_disk_bytes
    }

    /// The repo/revision/file this entry points at, or `None` if its URL is not
    /// a `resolve` URL.
    #[must_use]
    pub fn source(&self) -> Option<HfSource<'_>> {
        HfSource::parse(&self.url)
    }

    /// The URL to actually fetch, applying the configured base-URL override
    /// (BR-16).
    ///
    /// `base_url` replaces the scheme, host and any path prefix; the
    /// repo/revision/file path is preserved verbatim, so a mirror serves the
    /// *same pinned artifact* and the `sha256` check keeps its meaning. Passing
    /// `None` — or a base that is not an absolute URL, or a catalog URL with no
    /// path — yields the catalog URL unchanged.
    ///
    /// ```
    /// # use teton_inference::Catalog;
    /// let entry = Catalog::bundled().get("qwen2.5-coder-1.5b").unwrap().clone();
    /// let mirrored = entry.download_url(Some("https://hf-mirror.example.com"));
    /// assert!(mirrored.starts_with("https://hf-mirror.example.com/Qwen/"));
    /// assert!(mirrored.ends_with(".gguf"));
    /// ```
    #[must_use]
    pub fn download_url(&self, base_url: Option<&str>) -> String {
        let Some(base) = base_url.map(str::trim).filter(|b| !b.is_empty()) else {
            return self.url.clone();
        };
        // A base with no scheme cannot name a host to rewrite to; leaving the
        // catalog URL alone beats emitting a syntactically broken one.
        // `Config::validate` rejects such values up front, so this is defence in
        // depth rather than the primary check.
        if !base.contains("://") {
            return self.url.clone();
        }
        let Some(path) = url_path(&self.url) else {
            return self.url.clone();
        };
        format!("{}{}", base.trim_end_matches('/'), path)
    }

    /// Checks the invariants the downloader and the integrity check depend on:
    /// a parseable `resolve` URL, an immutable 40-hex revision that agrees with
    /// the URL (BR-15), and a well-formed SHA-256.
    ///
    /// # Errors
    /// Returns the first violated invariant as a [`CatalogError`] whose message
    /// names the entry and the remedy.
    pub fn validate(&self) -> Result<(), CatalogError> {
        let source = self.source().ok_or_else(|| CatalogError::UnpinnableUrl {
            name: self.name.clone(),
            url: self.url.clone(),
        })?;

        for revision in [self.revision.as_str(), source.revision] {
            if MOVING_REFS.contains(&revision.to_ascii_lowercase().as_str())
                || revision.starts_with("refs/")
            {
                return Err(CatalogError::MovingRevision {
                    name: self.name.clone(),
                    revision: revision.to_owned(),
                });
            }
            if !is_lower_hex(revision, 40) {
                return Err(CatalogError::MalformedRevision {
                    name: self.name.clone(),
                    revision: revision.to_owned(),
                });
            }
        }

        if self.revision != source.revision {
            return Err(CatalogError::RevisionMismatch {
                name: self.name.clone(),
                declared: self.revision.clone(),
                in_url: source.revision.to_owned(),
            });
        }

        if !is_lower_hex(&self.sha256, 64) {
            return Err(CatalogError::MalformedDigest {
                name: self.name.clone(),
                sha256: self.sha256.clone(),
            });
        }

        Ok(())
    }
}

/// A versioned set of model entries.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Catalog {
    /// Monotonic catalog version; lets the daemon detect a newer catalog.
    pub version: u32,
    /// The models, in author order.
    #[serde(default)]
    pub models: Vec<ModelEntry>,
}

impl Catalog {
    /// The default catalog embedded in the binary.
    ///
    /// # Panics
    /// Panics only if the in-repo `data/models.toml` is malformed — a build-time
    /// bug caught by the crate's own tests, never a runtime condition.
    #[must_use]
    pub fn bundled() -> Self {
        Self::from_toml(BUNDLED_TOML).expect("bundled model catalog must parse")
    }

    /// Parse a catalog from a TOML document.
    ///
    /// # Errors
    /// Returns the underlying TOML deserialization error on malformed input.
    pub fn from_toml(input: &str) -> Result<Self, toml::de::Error> {
        toml::from_str(input)
    }

    /// The entry named `name`, if present.
    #[must_use]
    pub fn get(&self, name: &str) -> Option<&ModelEntry> {
        self.models.iter().find(|m| m.name == name)
    }

    /// Checks every entry's invariants and that model names are unique.
    ///
    /// Parsing a catalog proves it is well-formed *TOML*; this proves it is a
    /// usable *catalog*. Callers that load a catalog from outside the binary
    /// (a daemon-supplied newer catalog) should run it before trusting the
    /// entries; the bundled catalog is asserted against it by this crate's
    /// tests, and `tools/refresh-catalog.py` is what keeps it satisfiable.
    ///
    /// # Errors
    /// Returns the first violation found, in entry order.
    pub fn validate(&self) -> Result<(), CatalogError> {
        let mut seen: Vec<&str> = Vec::with_capacity(self.models.len());
        for model in &self.models {
            model.validate()?;
            if seen.contains(&model.name.as_str()) {
                return Err(CatalogError::DuplicateName {
                    name: model.name.clone(),
                });
            }
            seen.push(&model.name);
        }
        Ok(())
    }

    /// The next smaller model that still fits `profile`, or `None` if `name` is
    /// already the smallest fitting model (or is absent).
    ///
    /// "Smaller" is strictly-lower `ram_floor_bytes`; the result is the *largest*
    /// such model that fits. Because each call returns a strictly-smaller model
    /// and the catalog is finite, repeatedly stepping down always terminates.
    #[must_use]
    pub fn step_down_from(&self, name: &str, profile: &HardwareProfile) -> Option<&ModelEntry> {
        let current = self.get(name)?;
        self.models
            .iter()
            .filter(|m| m.ram_floor_bytes < current.ram_floor_bytes && m.fits(profile))
            .max_by_key(|m| (m.ram_floor_bytes, m.size_bytes))
    }

    /// All models strictly smaller than `base` that fit `profile`, largest
    /// first. This is the ordered downgrade chain the pressure watcher walks.
    #[must_use]
    pub fn models_smaller_than(&self, base: &str, profile: &HardwareProfile) -> Vec<String> {
        let Some(base_entry) = self.get(base) else {
            return Vec::new();
        };
        let mut smaller: Vec<&ModelEntry> = self
            .models
            .iter()
            .filter(|m| m.ram_floor_bytes < base_entry.ram_floor_bytes && m.fits(profile))
            .collect();
        smaller.sort_by_key(|m| std::cmp::Reverse((m.ram_floor_bytes, m.size_bytes)));
        smaller.into_iter().map(|m| m.name.clone()).collect()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::probe::{GpuClass, HardwareProfile};

    fn big_machine() -> HardwareProfile {
        HardwareProfile {
            ram_bytes: 64 * 1024 * 1024 * 1024,
            free_disk_bytes: 500 * 1_000_000_000,
            gpu: GpuClass::AppleSilicon,
        }
    }

    const SHA: &str = "cc324af070c2ecbfd324a30884d2f951a7ff756aba85cb811a6ec436933bb046";
    const REV: &str = "f86cb2c1fa58255f8052cc32aeede1b7482d4361";

    /// A valid entry, so each test can perturb exactly one field.
    fn entry() -> ModelEntry {
        ModelEntry {
            name: "test-model".to_owned(),
            url: format!("https://huggingface.co/Acme/Acme-GGUF/resolve/{REV}/acme-q4_k_m.gguf"),
            revision: REV.to_owned(),
            sha256: SHA.to_owned(),
            size_bytes: 1_000,
            ram_floor_bytes: 2_000,
            band: TierBand::Small,
        }
    }

    #[test]
    fn bundled_catalog_parses_and_has_the_expected_models() {
        let catalog = Catalog::bundled();
        assert_eq!(catalog.version, 1);
        let names: Vec<&str> = catalog.models.iter().map(|m| m.name.as_str()).collect();
        assert_eq!(
            names,
            [
                "qwen2.5-coder-1.5b",
                "qwen2.5-coder-3b",
                "qwen2.5-coder-7b",
                "qwen3-coder-30b-a3b",
            ]
        );
    }

    #[test]
    fn bundled_shas_are_well_formed_hex() {
        for model in Catalog::bundled().models {
            assert_eq!(model.sha256.len(), 64, "{}", model.name);
            assert!(
                model.sha256.chars().all(|c| c.is_ascii_hexdigit()),
                "{} sha is not hex",
                model.name
            );
        }
    }

    #[test]
    fn bands_ascend_with_ram_floor() {
        assert!(TierBand::Small < TierBand::Mid);
        assert!(TierBand::Mid < TierBand::Large);
        // In the bundled catalog, larger bands carry larger RAM floors.
        let catalog = Catalog::bundled();
        let small = catalog.get("qwen2.5-coder-3b").unwrap();
        let mid = catalog.get("qwen2.5-coder-7b").unwrap();
        assert!(small.ram_floor_bytes < mid.ram_floor_bytes);
        assert_eq!(small.band, TierBand::Small);
        assert_eq!(mid.band, TierBand::Mid);
    }

    #[test]
    fn step_down_walks_strictly_smaller_and_terminates() {
        let catalog = Catalog::bundled();
        let profile = big_machine();
        // 7b -> 3b -> 1.5b -> None
        let a = catalog
            .step_down_from("qwen2.5-coder-7b", &profile)
            .unwrap();
        assert_eq!(a.name, "qwen2.5-coder-3b");
        let b = catalog.step_down_from(&a.name, &profile).unwrap();
        assert_eq!(b.name, "qwen2.5-coder-1.5b");
        assert!(catalog.step_down_from(&b.name, &profile).is_none());
    }

    #[test]
    fn step_down_skips_models_that_do_not_fit_disk() {
        let catalog = Catalog::bundled();
        // Enough RAM for anything, but only ~1.5 GB free disk: from 7b the only
        // smaller model that fits on disk is the 1.5b (~1.1 GB), not the 3b (~2 GB).
        let profile = HardwareProfile {
            ram_bytes: 64 * 1024 * 1024 * 1024,
            free_disk_bytes: 1_500_000_000,
            gpu: GpuClass::Cpu,
        };
        let next = catalog
            .step_down_from("qwen2.5-coder-7b", &profile)
            .unwrap();
        assert_eq!(next.name, "qwen2.5-coder-1.5b");
    }

    #[test]
    fn downgrade_chain_is_largest_first() {
        let catalog = Catalog::bundled();
        let chain = catalog.models_smaller_than("qwen2.5-coder-7b", &big_machine());
        assert_eq!(chain, ["qwen2.5-coder-3b", "qwen2.5-coder-1.5b"]);
        // Smallest model has an empty chain.
        assert!(catalog
            .models_smaller_than("qwen2.5-coder-1.5b", &big_machine())
            .is_empty());
    }

    #[test]
    fn unknown_model_has_no_step_down_and_no_chain() {
        let catalog = Catalog::bundled();
        assert!(catalog.step_down_from("ghost", &big_machine()).is_none());
        assert!(catalog
            .models_smaller_than("ghost", &big_machine())
            .is_empty());
    }

    #[test]
    fn catalog_round_trips_through_toml() {
        let catalog = Catalog::bundled();
        let toml_text = toml::to_string(&catalog).expect("serialize");
        let back = Catalog::from_toml(&toml_text).expect("deserialize");
        assert_eq!(catalog, back);
        // The round trip must carry the pin, not just the numbers.
        for (before, after) in catalog.models.iter().zip(&back.models) {
            assert_eq!(before.revision, after.revision, "{}", before.name);
            assert!(after.url.contains(&after.revision), "{}", after.name);
        }
    }

    // ---- BR-15: revision pinning -------------------------------------------

    #[test]
    fn bundled_catalog_validates() {
        Catalog::bundled()
            .validate()
            .expect("bundled catalog is valid");
    }

    #[test]
    fn bundled_entries_pin_hf_resolve_urls_at_forty_hex_revisions() {
        for model in Catalog::bundled().models {
            let source = model.source().unwrap_or_else(|| panic!("{}", model.name));
            assert!(
                model.url.starts_with("https://huggingface.co/"),
                "{} is not hosted on HuggingFace (ADR-004)",
                model.name
            );
            assert_eq!(source.revision, model.revision, "{}", model.name);
            assert!(is_lower_hex(source.revision, 40), "{}", model.name);
            assert!(source.file.ends_with(".gguf"), "{}", model.name);
            assert!(!source.repo.is_empty(), "{}", model.name);
        }
    }

    #[test]
    fn validate_rejects_moving_refs() {
        // Table of the refs a well-meaning editor actually reaches for.
        for git_ref in ["main", "master", "HEAD", "latest", "dev", "refs/heads/main"] {
            let mut model = entry();
            model.revision = git_ref.to_owned();
            model.url =
                format!("https://huggingface.co/Acme/Acme-GGUF/resolve/{git_ref}/acme-q4_k_m.gguf");
            let err = model.validate().expect_err(git_ref);
            assert!(
                matches!(err, CatalogError::MovingRevision { ref revision, .. } if revision == git_ref),
                "{git_ref} produced {err:?}"
            );
            let message = err.to_string();
            assert!(message.contains("moving ref"), "{message}");
            assert!(message.contains("refresh-catalog.py"), "{message}");
            assert!(message.contains("test-model"), "{message}");
        }
    }

    #[test]
    fn validate_rejects_revisions_that_are_not_commit_shas() {
        // (revision, why it is wrong)
        let cases = [
            ("f86cb2c", "abbreviated"),
            ("", "empty-ish"),
            ("v0.1.0", "a tag"),
            ("F86CB2C1FA58255F8052CC32AEEDE1B7482D4361", "uppercase hex"),
            ("f86cb2c1fa58255f8052cc32aeede1b7482d4361a", "41 chars"),
            ("g86cb2c1fa58255f8052cc32aeede1b7482d4361", "non-hex digit"),
        ];
        for (revision, why) in cases {
            let mut model = entry();
            model.revision = revision.to_owned();
            model.url = format!(
                "https://huggingface.co/Acme/Acme-GGUF/resolve/{revision}/acme-q4_k_m.gguf"
            );
            let err = model.validate().expect_err(why);
            // An empty revision collapses the URL, so it is unpinnable rather
            // than merely malformed — both are rejections, which is the point.
            assert!(
                matches!(
                    err,
                    CatalogError::MalformedRevision { .. } | CatalogError::UnpinnableUrl { .. }
                ),
                "{why}: {err:?}"
            );
            assert!(err.to_string().contains("test-model"), "{why}");
        }
    }

    #[test]
    fn validate_rejects_a_url_that_is_not_a_resolve_url() {
        let mut model = entry();
        model.url = "https://models.example.com/acme-q4_k_m.gguf".to_owned();
        let err = model.validate().expect_err("no resolve segment");
        assert!(matches!(err, CatalogError::UnpinnableUrl { .. }), "{err:?}");
        assert!(err.to_string().contains("40-hex-commit-sha"));
    }

    #[test]
    fn validate_rejects_a_revision_field_that_disagrees_with_the_url() {
        let other = "0123456789abcdef0123456789abcdef01234567";
        let mut model = entry();
        model.revision = other.to_owned();
        let err = model.validate().expect_err("mismatch");
        assert!(
            matches!(err, CatalogError::RevisionMismatch { ref declared, ref in_url, .. }
                if declared == other && in_url == REV),
            "{err:?}"
        );
    }

    #[test]
    fn validate_rejects_a_malformed_digest() {
        for bad in ["", "deadbeef", &SHA.to_uppercase(), &format!("{SHA}00")] {
            let mut model = entry();
            model.sha256 = bad.to_owned();
            let err = model.validate().expect_err(bad);
            assert!(
                matches!(err, CatalogError::MalformedDigest { .. }),
                "{err:?}"
            );
        }
    }

    #[test]
    fn validate_rejects_duplicate_model_names() {
        let catalog = Catalog {
            version: 1,
            models: vec![entry(), entry()],
        };
        let err = catalog.validate().expect_err("duplicate names");
        assert!(
            matches!(err, CatalogError::DuplicateName { ref name } if name == "test-model"),
            "{err:?}"
        );
    }

    // ---- BR-16: base-URL override ------------------------------------------

    #[test]
    fn base_url_override_rewrites_the_host_and_keeps_the_pinned_path() {
        let model = entry();
        assert_eq!(
            model.download_url(Some("https://hf-mirror.example.com")),
            format!("https://hf-mirror.example.com/Acme/Acme-GGUF/resolve/{REV}/acme-q4_k_m.gguf")
        );
    }

    #[test]
    fn base_url_override_honours_a_path_prefix_and_trailing_slashes() {
        let model = entry();
        let expected =
            format!("http://mirror.corp.internal/hf/Acme/Acme-GGUF/resolve/{REV}/acme-q4_k_m.gguf");
        for base in [
            "http://mirror.corp.internal/hf",
            "http://mirror.corp.internal/hf/",
            "  http://mirror.corp.internal/hf  ",
        ] {
            assert_eq!(model.download_url(Some(base)), expected, "base = {base:?}");
        }
    }

    #[test]
    fn base_url_override_preserves_the_repo_revision_and_file_exactly() {
        // The mirror must serve the *same pinned artifact*, or the sha256 check
        // stops meaning anything.
        let model = entry();
        let mirrored = model.download_url(Some("https://mirror.example.com"));
        let source = HfSource::parse(&mirrored).expect("still a resolve URL");
        let original = model.source().expect("catalog URL parses");
        assert_eq!(
            (source.repo, source.revision, source.file),
            (original.repo, original.revision, original.file)
        );
    }

    #[test]
    fn no_override_yields_the_catalog_url() {
        let model = entry();
        for base in [None, Some(""), Some("   ")] {
            assert_eq!(model.download_url(base), model.url, "base = {base:?}");
        }
    }

    #[test]
    fn a_base_without_a_scheme_is_ignored_rather_than_producing_a_broken_url() {
        // `Config::validate` rejects these first; this is the defence in depth.
        let model = entry();
        assert_eq!(model.download_url(Some("mirror.example.com")), model.url);
    }

    #[test]
    fn every_bundled_entry_is_mirrorable() {
        for model in Catalog::bundled().models {
            let mirrored = model.download_url(Some("https://mirror.example.com"));
            assert!(
                mirrored.starts_with("https://mirror.example.com/"),
                "{}",
                model.name
            );
            assert!(mirrored.contains(&model.revision), "{}", model.name);
        }
    }
}
